/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module output_hex_converter_1 (
    input [15:0] data,
    output reg [15:0] out_hex
  );
  
  
  
  always @* begin
    out_hex[0+3-:4] = data[0+3-:4];
    out_hex[4+3-:4] = data[4+3-:4];
    out_hex[8+3-:4] = data[8+3-:4];
    out_hex[12+3-:4] = data[12+3-:4];
  end
endmodule
