/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_33 (
    input [2:0] zvn,
    input [5:0] alufn_signal,
    output reg out
  );
  
  
  
  reg z;
  reg v;
  reg n;
  
  always @* begin
    z = zvn[2+0-:1];
    v = zvn[1+0-:1];
    n = zvn[0+0-:1];
    out = 16'h0000;
    
    case (alufn_signal)
      6'h33: begin
        out = z;
      end
      6'h35: begin
        out = n ^ v;
      end
      6'h37: begin
        out = z | (n ^ v);
      end
      default: begin
        out = 1'h0;
      end
    endcase
  end
endmodule
