/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module final_outputs_17 (
    input [15:0] led_a,
    input [15:0] led_b,
    input [15:0] led_c,
    output reg [15:0] out_a,
    output reg [15:0] out_b,
    output reg [15:0] out_c
  );
  
  
  
  always @* begin
    out_a = ((led_a + 3'h4) / 4'h8) * 4'h8;
    out_b = ((led_b + 3'h4) / 4'h8) * 4'h8;
    out_c = ((led_c + 3'h4) / 4'h8) * 4'h8;
  end
endmodule
